import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const foods = [
  // ── Proteins ──
  {
    name: 'Chicken Breast (cooked)',
    servingSize: '100g',
    servingWeightG: 100,
    calories: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 74,
    cholesterolMg: 85,
    saturatedFatG: 1,
    potassiumMg: 256,
    vitaminDMcg: 0,
    calciumMg: 15,
    ironMg: 1,
  },
  {
    name: 'Salmon (cooked)',
    servingSize: '100g',
    servingWeightG: 100,
    calories: 208,
    proteinG: 20,
    carbsG: 0,
    fatG: 13,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 59,
    cholesterolMg: 63,
    saturatedFatG: 3.1,
    potassiumMg: 363,
    vitaminDMcg: 11,
    calciumMg: 12,
    ironMg: 0.8,
  },
  {
    name: 'Eggs (large, whole)',
    servingSize: '1 egg',
    servingWeightG: 50,
    calories: 72,
    proteinG: 6,
    carbsG: 0.4,
    fatG: 5,
    fiberG: 0,
    sugarG: 0.2,
    sodiumMg: 71,
    cholesterolMg: 186,
    saturatedFatG: 1.6,
    potassiumMg: 69,
    vitaminDMcg: 1.1,
    calciumMg: 28,
    ironMg: 0.9,
  },
  {
    name: 'Ground Beef 85% Lean (cooked)',
    servingSize: '100g',
    servingWeightG: 100,
    calories: 215,
    proteinG: 26,
    carbsG: 0,
    fatG: 12,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 72,
    cholesterolMg: 86,
    saturatedFatG: 4.6,
    potassiumMg: 318,
    vitaminDMcg: 0,
    calciumMg: 18,
    ironMg: 2.7,
  },
  {
    name: 'Tuna (canned in water)',
    servingSize: '100g',
    servingWeightG: 100,
    calories: 109,
    proteinG: 25,
    carbsG: 0,
    fatG: 0.5,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 306,
    cholesterolMg: 36,
    saturatedFatG: 0.2,
    potassiumMg: 279,
    vitaminDMcg: 3.8,
    calciumMg: 11,
    ironMg: 1.3,
  },
  {
    name: 'Greek Yogurt (plain, non-fat)',
    servingSize: '1 cup (245g)',
    servingWeightG: 245,
    calories: 137,
    proteinG: 23,
    carbsG: 9,
    fatG: 0.7,
    fiberG: 0,
    sugarG: 9,
    sodiumMg: 94,
    cholesterolMg: 9,
    saturatedFatG: 0.2,
    potassiumMg: 342,
    vitaminDMcg: 0,
    calciumMg: 261,
    ironMg: 0.2,
  },
  {
    name: 'Cottage Cheese (2%)',
    servingSize: '1/2 cup (113g)',
    servingWeightG: 113,
    calories: 90,
    proteinG: 12,
    carbsG: 5,
    fatG: 2.5,
    fiberG: 0,
    sugarG: 4,
    sodiumMg: 380,
    cholesterolMg: 15,
    saturatedFatG: 1.5,
    potassiumMg: 110,
    vitaminDMcg: 0,
    calciumMg: 110,
    ironMg: 0,
  },
  {
    name: 'Tofu (firm)',
    servingSize: '100g',
    servingWeightG: 100,
    calories: 76,
    proteinG: 8,
    carbsG: 2,
    fatG: 4.3,
    fiberG: 0.3,
    sugarG: 0.6,
    sodiumMg: 7,
    cholesterolMg: 0,
    saturatedFatG: 0.6,
    potassiumMg: 121,
    vitaminDMcg: 0,
    calciumMg: 350,
    ironMg: 1.6,
  },

  // ── Grains & Carbs ──
  {
    name: 'Brown Rice (cooked)',
    servingSize: '1 cup (195g)',
    servingWeightG: 195,
    calories: 216,
    proteinG: 5,
    carbsG: 45,
    fatG: 1.8,
    fiberG: 3.5,
    sugarG: 0.7,
    sodiumMg: 10,
    cholesterolMg: 0,
    saturatedFatG: 0.4,
    potassiumMg: 154,
    vitaminDMcg: 0,
    calciumMg: 20,
    ironMg: 1,
  },
  {
    name: 'White Rice (cooked)',
    servingSize: '1 cup (186g)',
    servingWeightG: 186,
    calories: 242,
    proteinG: 4.4,
    carbsG: 53,
    fatG: 0.4,
    fiberG: 0.6,
    sugarG: 0,
    sodiumMg: 2,
    cholesterolMg: 0,
    saturatedFatG: 0.1,
    potassiumMg: 55,
    vitaminDMcg: 0,
    calciumMg: 16,
    ironMg: 2.7,
  },
  {
    name: 'Oats (dry rolled)',
    servingSize: '1/2 cup (40g)',
    servingWeightG: 40,
    calories: 150,
    proteinG: 5,
    carbsG: 27,
    fatG: 2.5,
    fiberG: 4,
    sugarG: 1,
    sodiumMg: 0,
    cholesterolMg: 0,
    saturatedFatG: 0.5,
    potassiumMg: 143,
    vitaminDMcg: 0,
    calciumMg: 21,
    ironMg: 2,
  },
  {
    name: 'Whole Wheat Bread',
    servingSize: '1 slice (28g)',
    servingWeightG: 28,
    calories: 69,
    proteinG: 3.6,
    carbsG: 12,
    fatG: 1,
    fiberG: 1.9,
    sugarG: 1.4,
    sodiumMg: 132,
    cholesterolMg: 0,
    saturatedFatG: 0.2,
    potassiumMg: 68,
    vitaminDMcg: 0,
    calciumMg: 30,
    ironMg: 1,
  },
  {
    name: 'Pasta (cooked)',
    servingSize: '1 cup (140g)',
    servingWeightG: 140,
    calories: 220,
    proteinG: 8,
    carbsG: 43,
    fatG: 1.3,
    fiberG: 2.5,
    sugarG: 0.6,
    sodiumMg: 1,
    cholesterolMg: 0,
    saturatedFatG: 0.3,
    potassiumMg: 61,
    vitaminDMcg: 0,
    calciumMg: 10,
    ironMg: 2.4,
  },
  {
    name: 'Sweet Potato (baked)',
    servingSize: '1 medium (130g)',
    servingWeightG: 130,
    calories: 112,
    proteinG: 2,
    carbsG: 26,
    fatG: 0.1,
    fiberG: 3.8,
    sugarG: 5.4,
    sodiumMg: 72,
    cholesterolMg: 0,
    saturatedFatG: 0,
    potassiumMg: 438,
    vitaminDMcg: 0,
    calciumMg: 43,
    ironMg: 0.8,
  },
  {
    name: 'Quinoa (cooked)',
    servingSize: '1 cup (185g)',
    servingWeightG: 185,
    calories: 222,
    proteinG: 8,
    carbsG: 39,
    fatG: 3.5,
    fiberG: 5,
    sugarG: 1.6,
    sodiumMg: 13,
    cholesterolMg: 0,
    saturatedFatG: 0.4,
    potassiumMg: 318,
    vitaminDMcg: 0,
    calciumMg: 31,
    ironMg: 2.8,
  },

  // ── Vegetables ──
  {
    name: 'Broccoli (raw)',
    servingSize: '1 cup (91g)',
    servingWeightG: 91,
    calories: 31,
    proteinG: 2.6,
    carbsG: 6,
    fatG: 0.3,
    fiberG: 2.4,
    sugarG: 1.5,
    sodiumMg: 30,
    cholesterolMg: 0,
    saturatedFatG: 0.1,
    potassiumMg: 288,
    vitaminDMcg: 0,
    calciumMg: 43,
    ironMg: 0.7,
  },
  {
    name: 'Spinach (raw)',
    servingSize: '1 cup (30g)',
    servingWeightG: 30,
    calories: 7,
    proteinG: 0.9,
    carbsG: 1.1,
    fatG: 0.1,
    fiberG: 0.7,
    sugarG: 0.1,
    sodiumMg: 24,
    cholesterolMg: 0,
    saturatedFatG: 0,
    potassiumMg: 167,
    vitaminDMcg: 0,
    calciumMg: 30,
    ironMg: 0.8,
  },
  {
    name: 'Avocado',
    servingSize: '1/2 avocado (68g)',
    servingWeightG: 68,
    calories: 110,
    proteinG: 1.3,
    carbsG: 6,
    fatG: 10,
    fiberG: 4.6,
    sugarG: 0.2,
    sodiumMg: 5,
    cholesterolMg: 0,
    saturatedFatG: 1.4,
    potassiumMg: 345,
    vitaminDMcg: 0,
    calciumMg: 12,
    ironMg: 0.4,
  },
  {
    name: 'Banana',
    servingSize: '1 medium (118g)',
    servingWeightG: 118,
    calories: 105,
    proteinG: 1.3,
    carbsG: 27,
    fatG: 0.4,
    fiberG: 3.1,
    sugarG: 14,
    sodiumMg: 1,
    cholesterolMg: 0,
    saturatedFatG: 0.1,
    potassiumMg: 422,
    vitaminDMcg: 0,
    calciumMg: 6,
    ironMg: 0.3,
  },
  {
    name: 'Apple',
    servingSize: '1 medium (182g)',
    servingWeightG: 182,
    calories: 95,
    proteinG: 0.5,
    carbsG: 25,
    fatG: 0.3,
    fiberG: 4.4,
    sugarG: 19,
    sodiumMg: 2,
    cholesterolMg: 0,
    saturatedFatG: 0,
    potassiumMg: 195,
    vitaminDMcg: 0,
    calciumMg: 11,
    ironMg: 0.2,
  },
  {
    name: 'Blueberries',
    servingSize: '1 cup (148g)',
    servingWeightG: 148,
    calories: 84,
    proteinG: 1.1,
    carbsG: 21,
    fatG: 0.5,
    fiberG: 3.6,
    sugarG: 15,
    sodiumMg: 1,
    cholesterolMg: 0,
    saturatedFatG: 0,
    potassiumMg: 114,
    vitaminDMcg: 0,
    calciumMg: 9,
    ironMg: 0.4,
  },

  // ── Fats & Dairy ──
  {
    name: 'Olive Oil',
    servingSize: '1 tbsp (14g)',
    servingWeightG: 14,
    calories: 119,
    proteinG: 0,
    carbsG: 0,
    fatG: 13.5,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 0,
    cholesterolMg: 0,
    saturatedFatG: 1.9,
    potassiumMg: 0,
    vitaminDMcg: 0,
    calciumMg: 0,
    ironMg: 0.1,
  },
  {
    name: 'Whole Milk',
    servingSize: '1 cup (244g)',
    servingWeightG: 244,
    calories: 149,
    proteinG: 8,
    carbsG: 12,
    fatG: 8,
    fiberG: 0,
    sugarG: 12,
    sodiumMg: 105,
    cholesterolMg: 24,
    saturatedFatG: 4.6,
    potassiumMg: 349,
    vitaminDMcg: 3.2,
    calciumMg: 276,
    ironMg: 0,
  },
  {
    name: 'Cheddar Cheese',
    servingSize: '1 oz (28g)',
    servingWeightG: 28,
    calories: 113,
    proteinG: 7,
    carbsG: 0.4,
    fatG: 9.3,
    fiberG: 0,
    sugarG: 0.1,
    sodiumMg: 185,
    cholesterolMg: 30,
    saturatedFatG: 5.9,
    potassiumMg: 28,
    vitaminDMcg: 0.1,
    calciumMg: 201,
    ironMg: 0.2,
  },
  {
    name: 'Almonds',
    servingSize: '1 oz (28g)',
    servingWeightG: 28,
    calories: 164,
    proteinG: 6,
    carbsG: 6,
    fatG: 14,
    fiberG: 3.5,
    sugarG: 1.2,
    sodiumMg: 0,
    cholesterolMg: 0,
    saturatedFatG: 1.1,
    potassiumMg: 200,
    vitaminDMcg: 0,
    calciumMg: 76,
    ironMg: 1.1,
  },
  {
    name: 'Peanut Butter (natural)',
    servingSize: '2 tbsp (32g)',
    servingWeightG: 32,
    calories: 190,
    proteinG: 8,
    carbsG: 6,
    fatG: 16,
    fiberG: 2,
    sugarG: 1,
    sodiumMg: 140,
    cholesterolMg: 0,
    saturatedFatG: 2.5,
    potassiumMg: 200,
    vitaminDMcg: 0,
    calciumMg: 17,
    ironMg: 0.6,
  },

  // ── Legumes ──
  {
    name: 'Black Beans (cooked)',
    servingSize: '1/2 cup (86g)',
    servingWeightG: 86,
    calories: 114,
    proteinG: 7.6,
    carbsG: 20,
    fatG: 0.5,
    fiberG: 7.5,
    sugarG: 0.3,
    sodiumMg: 1,
    cholesterolMg: 0,
    saturatedFatG: 0.1,
    potassiumMg: 305,
    vitaminDMcg: 0,
    calciumMg: 23,
    ironMg: 1.8,
  },
  {
    name: 'Lentils (cooked)',
    servingSize: '1/2 cup (99g)',
    servingWeightG: 99,
    calories: 115,
    proteinG: 9,
    carbsG: 20,
    fatG: 0.4,
    fiberG: 7.8,
    sugarG: 1.8,
    sodiumMg: 2,
    cholesterolMg: 0,
    saturatedFatG: 0.1,
    potassiumMg: 365,
    vitaminDMcg: 0,
    calciumMg: 19,
    ironMg: 3.3,
  },
];

async function main() {
  console.log('Seeding food database...');

  for (const food of foods) {
    await prisma.food.upsert({
      where: { id: food.name }, // fallback — won't match, so always creates
      update: {},
      create: food,
    }).catch(async () => {
      // If upsert fails (id mismatch), just create
      const existing = await prisma.food.findFirst({ where: { name: food.name } });
      if (!existing) {
        await prisma.food.create({ data: food });
      }
    });
  }

  console.log(`Seeded ${foods.length} foods.`);

  // Demo user (optional — remove in production)
  const demoPasswordHash = await bcrypt.hash('demo1234', 12);
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@vitra.app' },
    update: { emailVerified: new Date() },
    create: {
      email: 'demo@vitra.app',
      name: 'Demo User',
      passwordHash: demoPasswordHash,
      emailVerified: new Date(),
      profile: {
        create: {
          sex: 'male',
          heightCm: 178,
          weightKg: 82,
          goal: 'maintain',
          activityLevel: 'moderately_active',
          caloricTarget: 2200,
          proteinTargetG: 150,
          carbTargetG: 250,
          fatTargetG: 70,
        },
      },
      subscriptionStatus: {
        create: { tier: 'pro' },
      },
    },
  });

  console.log(`Demo user ready: ${demoUser.email}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
